<!DOCTYPE  html>
<html>
    <head>
        <?php include dirname( __FILE__) . "/../includes/head.php"; ?>
    </head>
    <body class="body">
<?php include dirname( __FILE__) . "/../includes/top.php"; ?>
        <div class="content">
<?php include dirname( __FILE__) . "/../includes/leftmenu.php"; ?>
            <div class="panel">
                <div class="panel_padding">
                    
		<form action="<?php echo config("site_root"); ?>/index.php/dev/Index/fields" method="post">
		    
			<select name="table_name">
				<option>select table name</option>
			<?php  for( $i=0; $i< count( $tableArray ); $i++ ): ?>
				<option value="<?php echo $tableArray[$i] ?>"><?php echo $tableArray[$i] ?></option>
			<?php  endfor; ?>
			</select><br/>
			<span title="">model name</span>
			<input type="text" value="" name="model_name" /><br/>
			<input type="submit" value="Next" title="next" />
		</form>
		
		Note:Please modify your mysql connection settings in /application/configs/config.php at first.<br />
		and then please create one or more tables in your MySQL database like this:<br />
		<pre>
		
CREATE TABLE IF NOT EXISTS `article` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT ' ',
  `content` text NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=27 ;
		</pre>
		after create talbe,please refresh this page ,your table should appear in the table name drop down list.<br />
		please choose a table to create the CRUD functions.<br />
                
                
                </div>
            </div>
            <div class="clear"></div>
        </div>
<?php include dirname( __FILE__) . "/../includes/bottom.php"; ?>
    </body>
</html>