<?php
$crlf = "\r\n";
?><!DOCTYPE  html>
<html>
    <head>
        <?php echo '<?php include dirname( __FILE__) . "/../includes/head.php"; ?>' . $crlf; ?>
    </head>
    <body class="body">
<?php echo '<?php include dirname( __FILE__) . "/../includes/top.php"; ?>' . $crlf; ?>
        <div class="content">
<?php echo '<?php include dirname( __FILE__) . "/../includes/leftmenu.php"; ?>' . $crlf; ?>
            <div class="panel">
                <div class="panel_padding">
                    <form action="<?php echo '<?php echo config("site_root"); ?>'; ?>/index.php/<?php echo ucfirst($class) ?>/saveEdit" method="post">
                        <table class="table">
<?php
                           // echo $crlf;
                            for ($i = 0; $i < $field_count; $i++):

                                $fieldName = $_POST["field_" . $i];

                                echo '                            <tr>' . $crlf;



                                echo '                                <td>' . $_POST[$fieldName . "_label"] . '</td>' . $crlf;
                                echo '                                <td> ';

                                switch ($_POST[$fieldName . "_form"]) {
                                    case "HtmlInputText":

                                        echo '<input type="text" name="'. $fieldName .'" value="<?php echo $row["' . $fieldName . '"]?>" />';

                                        break;
                                }

                                echo '</td>' . $crlf;
                                echo '                            </tr>' . $crlf;
                            endfor;
    ?>
                        </table>
                        <input type="submit" value="save" />
                    </form>
                </div>
            </div>
            <div class="clear"></div>
        </div>
<?php echo '<?php include dirname( __FILE__) . "/../includes/bottom.php"; ?>' . $crlf; ?>
    </body>
</html>