<?php
$crlf = "\r\n";
?><!DOCTYPE  html>
<html>
    <head>
        <?php echo '<?php include dirname( __FILE__) . "/../includes/head.php"; ?>' . $crlf; ?>
    </head>
    <body class="body">
<?php echo '<?php include dirname( __FILE__) . "/../includes/top.php"; ?>' . $crlf; ?>
        <div class="content">
<?php echo '<?php include dirname( __FILE__) . "/../includes/leftmenu.php"; ?>' . $crlf; ?>
            <div class="panel">
                <div class="panel_padding">
                    <h1><?php echo $model_name ?></h1>
                    <form action="" method="get">
                    <table class="table">
                        <tr>
<?php 
for ($i = 0; $i < count($fields); $i++): 
       echo "                            <th>".  $_POST[$fields[$i]["Field"] . "_label"] ."</th>" . $crlf;
endfor; 
?>
                            <th></th>
                        </tr>
                        <tr>
<?php 
for ($i = 0; $i < count($fields); $i++): 
       echo "                            <td><input type=\"text\" style=\"width:100%\" name=\"".  $_POST["field_" . $i ] ."\" value=\"<?php echo \$_GET[\"".$_POST["field_" . $i ]."\"]; ?>\"/></td>" . $crlf;
endfor; 
?>
                           <td><input type="submit" value="query" />    <input type="hidden" name="PageSize" value="<?php echo '<?php echo  $_GET["PageSize"]; ?>';?>" /> </td>   
                        </tr>
                        <?php echo "<?php " ?> for( $i=0; $i< count( $Data); $i++ ):  $item = $Data[$i]; ?>
                        <tr>
<?php for ($i = 0; $i < $field_count; $i++): $fieldName = $_POST["field_" . $i]; 

       echo "                            <td><?php echo \$item[\"". $fieldName ."\"]; ?> </td>" . $crlf;

 endfor; ?>
                            <td>
                                <a href="<?php echo '<?php echo config("site_root"); ?>'; ?>/index.php/<?php echo ucfirst($class) ?>/show?<?php echo $priQueryStr ?>">show</a>
                            </td>
                        </tr>
                        <?php echo "<?" ?> endfor; ?>

                    </table>
                    </form>
                    <div class="PageLink"><?php echo "<?php echo \$pagebar?>" ?></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
<?php echo '<?php include dirname( __FILE__) . "/../includes/bottom.php"; ?>' . $crlf; ?>
    </body>
</html>