<!DOCTYPE  html>
<html>
    <head>
        <?php include dirname( __FILE__) . "/../includes/head.php"; ?>
    </head>
    <body class="body">
<?php include dirname( __FILE__) . "/../includes/top.php"; ?>
        <div class="content">
<?php include dirname( __FILE__) . "/../includes/leftmenu.php"; ?>
            <div class="panel">
                <div class="panel_padding">
                    <form action="/index.php/Rent/saveEdit" method="post">
                        <table class="table">
                            <tr>
                                <td>stu_id</td>
                                <td> <input type="text" name="stu_id" value="<?php echo $row["stu_id"]?>" /></td>
                            </tr>
                            <tr>
                                <td>book_id</td>
                                <td> <input type="text" name="book_id" value="<?php echo $row["book_id"]?>" /></td>
                            </tr>
                            <tr>
                                <td>date</td>
                                <td> <input type="text" name="date" value="<?php echo $row["date"]?>" /></td>
                            </tr>
                        </table>
                        <input type="submit" value="save" />
                    </form>
                </div>
            </div>
            <div class="clear"></div>
        </div>
<?php include dirname( __FILE__) . "/../includes/bottom.php"; ?>
    </body>
</html>