<!DOCTYPE  html>
<html>
    <head>
        <?php include dirname( __FILE__) . "/../includes/head.php"; ?>
    </head>
    <body class="body">
<?php include dirname( __FILE__) . "/../includes/top.php"; ?>
        <div class="content">
<?php include dirname( __FILE__) . "/../includes/leftmenu.php"; ?>
            <div class="panel">
                <div class="panel_padding">
                    <form action="<?php echo config("site_root"); ?>/index.php/Task/saveEdit" method="post">
                        <table class="table">
                            <tr>
                                <td>id</td>
                                <td> <input type="text" name="id" value="<?php echo $row["id"]?>" /></td>
                            </tr>
                            <tr>
                                <td>title</td>
                                <td> <input type="text" name="title" value="<?php echo $row["title"]?>" /></td>
                            </tr>
                            <tr>
                                <td>content</td>
                                <td> <input type="text" name="content" value="<?php echo $row["content"]?>" /></td>
                            </tr>
                        </table>
                        <input type="submit" value="save" />
                    </form>
                </div>
            </div>
            <div class="clear"></div>
        </div>
<?php include dirname( __FILE__) . "/../includes/bottom.php"; ?>
    </body>
</html>