<!DOCTYPE  html>
<html>
    <head>
        <?php include dirname( __FILE__) . "/../includes/head.php"; ?>
    </head>
    <body class="body">
<?php include dirname( __FILE__) . "/../includes/top.php"; ?>
        <div class="content">
<?php include dirname( __FILE__) . "/../includes/leftmenu.php"; ?>
            <div class="panel">
                <div class="panel_padding">
                    <h1>task</h1>
                    <a href="<?php echo config("site_root"); ?>/index.php/Task/add">new</a>
                    <form action="" method="get">
                    <table class="table">
                        <tr>
                            <th>id</th>
                            <th>title</th>
                            <th>content</th>
                            <th></th>
                        </tr>
                        <tr>
                            <td><input type="text" style="width:100%"  name="id" value="<?php echo $_GET["id"]; ?>"/></td>
                            <td><input type="text" style="width:100%"  name="title" value="<?php echo $_GET["title"]; ?>"/></td>
                            <td><input type="text" style="width:100%"  name="content" value="<?php echo $_GET["content"]; ?>"/></td>
                           <td><input type="submit" value="query" />    <input type="hidden" name="PageSize" value="<?php echo  $_GET["PageSize"]; ?>" /> </td>   
                        </tr>
                        <?php  for( $i=0; $i< count( $Data); $i++ ): $item = $Data[$i]; ?>
                        <tr>
                            <td><?php echo $item["id"]; ?> </td>
                            <td><?php echo $item["title"]; ?> </td>
                            <td><?php echo $item["content"]; ?> </td>
                            <td>
                                <a href="<?php echo config("site_root"); ?>/index.php/Task/edit?id=<?=$Data[$i]["id"]?>">edit</a>
                                <a href="<?php echo config("site_root"); ?>/index.php/Task/delete?id=<?=$Data[$i]["id"]?>">delete</a>
                            </td>
                        </tr>
                        <? endfor; ?>

                    </table>
                    </form>
                    <div class="PageLink"><?php echo $pagebar?></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
<?php include dirname( __FILE__) . "/../includes/bottom.php"; ?>
    </body>
</html>