<!DOCTYPE  html>
<html>
    <head>
        <?php include dirname( __FILE__) . "/../includes/head.php"; ?>
    </head>
    <body class="body">
<?php include dirname( __FILE__) . "/../includes/top.php"; ?>
        <div class="content">
<?php include dirname( __FILE__) . "/../includes/leftmenu.php"; ?>
            <div class="panel">
                <div class="panel_padding">
                    <a href="<?php echo config("site_root"); ?>/index.php/Task/index">&lt;&lt;</a>
                    <table class="table">
                        <tr>
                            <td>id</td>
                            <td><?php echo $row["id"]?></td>
                        </tr>
                        <tr>
                            <td>title</td>
                            <td><?php echo $row["title"]?></td>
                        </tr>
                        <tr>
                            <td>content</td>
                            <td><?php echo $row["content"]?></td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="clear"></div>
        </div>
<?php include dirname( __FILE__) . "/../includes/bottom.php"; ?>
    </body>
</html>