<?php

$crlf = "\r\n";
echo '<?php ' . $crlf;
echo 'require_once  "Rong/Controller.php";' . $crlf;

echo 'require_once ROOT . "/application/models/' . ucfirst($class) . 'Model.php"; ' . $crlf;
echo 'class ' . ucfirst($class) . 'Controller  extends Rong_Controller ' . $crlf;
echo '{' . $crlf;
if (@$need_create == true):

    echo '    /**' . $crlf;
    echo '    *@function : Display a interface for input' . $crlf;
    echo '    */' . $crlf;
    echo '    public function addAction()' . $crlf;
    echo '    {' . $crlf;
    echo '        $data = array();' . $crlf;
    echo '        $this->view->display( "' . strtolower($class) . '/add.phtml" , $data );' . $crlf;
    echo '    }' . $crlf. $crlf. $crlf;
    echo '    ' . $crlf;
    
    
    echo '    /**' . $crlf;
    echo '    *@function : save data to database what the user have added' . $crlf;
    echo '    */' . $crlf;
    echo '    public function saveAddAction()' . $crlf;
    echo '    {' . $crlf;

    $fieldsList = "";
    for ($i = 0; $i < count($fields); $i++) :
        echo '        $' . $fields[$i]["Field"] . ' = $_POST["' . $fields[$i]["Field"] . '"];' . $crlf;
        $fieldsList .= ( $i == 0 ) ? "" : ",";
        $fieldsList .= "\$" . $fields[$i]["Field"];
    endfor;

    echo '        $db = load_database();' . $crlf;
    echo '        $' . strtolower($class) . 'Model = new ' . ucfirst($class) . 'Model();' . $crlf;
    echo '        $lastId = $' . strtolower($class) . 'Model->insert( ' . $fieldsList . ' );' . $crlf;
    echo '        $msg = "' . $class . ' was save successfully!";' . $crlf;
    echo '        $msg .= db_debug("<br /><b>sql debug</b><br />last insert id:" . $lastId . "<br />mysql error:" . $' . strtolower($class) . 'Model->db->error() );' . $crlf;
    echo '        MessagePanel::show( $msg , url("/' . strtolower($class) . '/manage"), 5000 );' . $crlf;
    echo '    }' . $crlf. $crlf. $crlf;

    
    
endif; //if$need_create == true 



if (@$need_update == true):

    echo '    /**' . $crlf;
    echo '    *@function : Display a interface for edit' . $crlf;
    echo '    */' . $crlf;
    echo '    public function editAction()' . $crlf;
    echo '    {' . $crlf;
    echo '        $data = array();' . $crlf;
    for ($i = 0; $i < count($priFields); $i++):
        echo '        $' . $priFields[$i]["Field"] . ' = $_GET["' . $priFields[$i]["Field"] . '"];' . $crlf;
    endfor;

    echo '        $db = load_database();' . $crlf;
    echo '        $' . strtolower($class) . 'Model = new ' . ucfirst($class) . 'Model();' . $crlf;
    echo '        $data["row"] = $row = $' . strtolower($class) . 'Model->fetchRow( "' . $priStr . '" );' . $crlf;
    echo '        $this->view->display( "' . strtolower($class) . '/edit.phtml" , $data );' . $crlf;
    echo '    }' . $crlf. $crlf. $crlf;

    
    
    echo '    /**' . $crlf;
    echo '    *@function : save data to database what the user have edited' . $crlf;
    echo '    */' . $crlf;
    echo '    public function saveEditAction()' . $crlf;
    echo '    {' . $crlf;
    echo '        $db = load_database();' . $crlf;
    for ($i = 0; $i < count($fields); $i++):
        echo '        $' . $fields[$i]["Field"] . ' = $_POST["' . $fields[$i]["Field"] . '"];' . $crlf;
    endfor;
    echo '        $' . strtolower($class) . 'Model = new ' . ucfirst($class) . 'Model();' . $crlf;
    echo '        $affectedRows = $' . strtolower($class) . 'Model->update( ' . $paramList . ' );' . $crlf;
    echo '        $msg = "' . $class . ' was updated successfully!";' . $crlf;
    echo '        $msg .= db_debug("<br /><b>sql debug</b><br />affected rows:" . $affectedRows . "<br />mysql error:" . $' . strtolower($class) . 'Model->db->error() );' . $crlf;
    echo '        MessagePanel::show( $msg , url("/' . strtolower($class) . '/manage"), 5000 );' . $crlf;
    echo '    }' . $crlf. $crlf. $crlf;

endif; //end of @need_read 


if (@$need_read == true):

    echo '    public function manageAction()' . $crlf;
    echo '    {' . $crlf;
    echo '        require_once "Rong/Html/PageLink.php";' . $crlf;
    echo '        $page = @$_GET["Page"];' . $crlf;
    echo '        $pageSize = @$_GET["PageSize"] ;' . $crlf;
    $field_list = "";
    $queryString = "";
    for ($i = 0; $i < count($fields); $i++):
        $field_list .= '$' . $fields[$i]["Field"]  . " , ";
        $queryString .= '&' . $fields[$i]["Field"] . '=" . $_GET["' . $fields[$i]["Field"] . '"] ."';
        echo '        $' . $fields[$i]["Field"] . ' = $_GET["' . $fields[$i]["Field"] . '"];' . $crlf;
    endfor;
    echo '        $urlTemplate = config("url_prefix_of_controller") . "/'. ucfirst( $class).'/index?Page={Page}&PageSize={PageSize}'. $queryString. '";' . $crlf;
   
    echo '        $db = load_database();' . $crlf;
    echo '        $' . strtolower($class) . 'Model = new ' . ucfirst($class) . 'Model();' . $crlf;
    echo '        $data = $result = $' . strtolower($class) . 'Model->manage( '.$field_list.' $page , $pageSize ,$urlTemplate );' . $crlf;
    
    echo '        $data["pagebar"] =$data["PaginatorHtml"];  ' . $crlf;
    echo '        $this->view->display( "' . strtolower($class) . '/manage.phtml" , $data );' . $crlf;
    echo '    }' . $crlf. $crlf. $crlf;

    
    
    
    echo '    public function indexAction()' . $crlf;
    echo '    {' . $crlf;
    echo '        require_once "Rong/Html/PageLink.php";' . $crlf;
    echo '        $page = @$_GET["Page"];' . $crlf;
    echo '        $pageSize = @$_GET["PageSize"] ;' . $crlf;
    $field_list = "";
    $queryString = "";
    for ($i = 0; $i < count($fields); $i++):
        $field_list .= '$' . $fields[$i]["Field"]  . " , ";
        $queryString .= '&' . $fields[$i]["Field"] . '=" . $_GET["' . $fields[$i]["Field"] . '"] ."';
        echo '        $' . $fields[$i]["Field"] . ' = $_GET["' . $fields[$i]["Field"] . '"];' . $crlf;
    endfor;
    echo '        $urlTemplate = config("url_prefix_of_controller") . "/'. ucfirst( $class).'/index?Page={Page}&PageSize={PageSize}'. $queryString. '";' . $crlf;
    echo '        $db = load_database();' . $crlf;
    echo '        $' . strtolower($class) . 'Model = new ' . ucfirst($class) . 'Model();' . $crlf;
    echo '        $data = $result = $' . strtolower($class) . 'Model->index( '.$field_list.'$page , $pageSize ,$urlTemplate );' . $crlf;
    echo '        $data["pagebar"] = $data["PaginatorHtml"];' . $crlf;
    echo '        $this->view->display( "' . strtolower($class) . '/index.phtml" , $data );' . $crlf;
    echo '    }' . $crlf. $crlf. $crlf;
    echo '    public function showAction()' . $crlf;
    echo '    {' . $crlf;
    echo '        $data = array();' . $crlf;
    for ($i = 0; $i < count($priFields); $i++):
        echo '        $' . $priFields[$i]["Field"] . ' = $_GET["' . $priFields[$i]["Field"] . '"];' . $crlf;
    endfor;
    echo '        $db = load_database();' . $crlf;
    echo '        $' . strtolower($class) . 'Model = new ' . ucfirst($class) . 'Model();' . $crlf;
    echo '        $data["row"] = $row = $' . strtolower($class) . 'Model->fetchRow( "' . $priStr . '" );' . $crlf;
    echo '        $this->view->display( "' . strtolower($class) . '/show.phtml" , $data );' . $crlf;
    echo '    }' . $crlf. $crlf. $crlf;

endif; //end of @need_read 



if (@$need_delete == true):
    echo '    public function deleteAction()' . $crlf;
    echo '    {' . $crlf;
    for ($i = 0; $i < count($priFields); $i++):
        echo '        $' . $priFields[$i]["Field"] . ' = $_GET["' . $priFields[$i]["Field"] . '"];' . $crlf;
    endfor;
    echo '        $db = load_database();' . $crlf;
    echo '        $' . strtolower($class) . 'Model = new ' . ucfirst($class) . 'Model();' . $crlf;
    echo '        $affectedRows = $' . strtolower($class) . 'Model->delete( "' . $priStr . '" );' . $crlf;
    echo '        $msg = "' . $class . ' was deleted successfully!";' . $crlf;
    echo '        $msg .= db_debug("<br /><b>sql debug</b><br />affected rows:" . $affectedRows . "<br />mysql error:" . $' . strtolower($class) . 'Model->db->error() );' . $crlf;
    echo '        MessagePanel::show( $msg , url("/' . strtolower($class) . '/manage"), 5000 );' . $crlf;
    echo '    }' . $crlf. $crlf. $crlf;
endif; //end of @need_delete 


echo '}' . $crlf; //end class
echo '?>' . $crlf;
?>