<?php

$crlf = "\r\n";

echo '<?php' . $crlf;
echo 'require_once "Rong/Db/Model.php";' . $crlf;
echo 'class ' . ucfirst($class) . 'Model extends Rong_Db_Model ' . $crlf;
echo '{' . $crlf;
echo '    public $_name = ""; ' . $crlf;
echo '    public function __construct( )' . $crlf;
echo '    {       ' . $crlf;
echo '        $this->setNameWithDefaultTablePrefix("' . strtolower($class) . '"); //init table name' . $crlf;
echo '        parent::__construct();' . $crlf;
echo '    }' . $crlf. $crlf . $crlf;
 

if (@$need_create == true):
    echo '   /**' . $crlf;
    echo '    @return int last insert id' . $crlf;
    echo '   */' . $crlf;
    echo '    public function insert( ' . $paramList . ')' . $crlf;
    echo '    {' . $crlf;
    echo '        $data = array(' . $crlf;
    for ($i = 0; $i < count($fields); $i++) :
        echo '            "' . $fields[$i]["Field"] . '" => $' . $fields[$i]["Field"] . ' ,' . $crlf;
    endfor;
    echo '        );' . $crlf;
    echo '        return parent::insert( $data );' . $crlf;
    echo '    }' . $crlf. $crlf . $crlf;
     
endif; //if$need_create == true 



if (@$need_update == true):
   echo '   /**' . $crlf;
    echo '    @return int affected rows' . $crlf;
    echo '   */' . $crlf;
    echo '    public function update( ' . $paramList . ' )' . $crlf;
    echo '    {' . $crlf;
    echo '        $data = array(' . $crlf;
    for ($i = 0; $i < count($commonFields); $i++) :
        echo '        "' . $commonFields[$i]["Field"] . '" => $' . $commonFields[$i]["Field"] . ' ,' . $crlf;
    endfor;
    echo '        );' . $crlf;
    echo '        return parent::update( $data , "' . $priStr . '");' . $crlf;
    echo '    }' . $crlf. $crlf . $crlf;
     
endif; //if$need_update == true 

if (@$need_read == true):
    
    echo '   /**' . $crlf;
    echo '    @return array $rs = array("Data"=>array(...),"PageLink"=> "string" )' . $crlf;
    echo '   */' . $crlf;
    $field_list = "";
    for ($i = 0; $i < count($fields); $i++):
        $field_list .= '$' . $fields[$i]["Field"]  . " , ";
       // echo '        $' . $fields[$i]["Field"] . ' = $_GET["' . $fields[$i]["Field"] . '"];' . $crlf;
    endfor;
    echo '    public function index( '.$field_list.'$page , $pageSize , $urlTemplate)' . $crlf;
    echo '    {' . $crlf;
    echo '        $sql = "select ' . $sqlFields . ' from " . $this->_name . " where 1 ";' . $crlf;
    for ($i = 0; $i < count($fields); $i++):
        //$field_list .= '$' . $fields[$i]["Field"]  . " , ";
       // echo '        $' . $fields[$i]["Field"] . ' = $_GET["' . $fields[$i]["Field"] . '"];' . $crlf;
        echo '        if( isset($' . $fields[$i]["Field"].') || trim($' . $fields[$i]["Field"] . ') != ""){ $sql .=" and ' . $fields[$i]["Field"] .' like \'%" . $this->escape( $' .$fields[$i]["Field"] .' ) . "%\'";}' . $crlf;
    endfor;
   
    echo '        return $this->db->getPaginator($sql, $page, $pageSize, $urlTemplate); ' . $crlf;
    echo '    }' . $crlf. $crlf . $crlf;
    
    echo '   /**' . $crlf;
    echo '    @return array $rs = array("Data"=>array(...),"PageLink"=> "string" )' . $crlf;
    echo '   */' . $crlf;
    
    echo '    public function manage( '. $field_list.'  $page , $pageSize , $urlTemplate)' . $crlf;
    echo '    {' . $crlf;
    echo '        $sql = "select ' . $sqlFields . ' from " . $this->_name . " where 1 ";' . $crlf;
    for ($i = 0; $i < count($fields); $i++):
        //$field_list .= '$' . $fields[$i]["Field"]  . " , ";
       // echo '        $' . $fields[$i]["Field"] . ' = $_GET["' . $fields[$i]["Field"] . '"];' . $crlf;
        echo '        if( isset($' . $fields[$i]["Field"].') || trim($' . $fields[$i]["Field"] . ') != ""){ $sql .=" and ' . $fields[$i]["Field"] .' like \'%" . $this->escape( $' .$fields[$i]["Field"] .' ) . "%\'";}' . $crlf;
    endfor;
    echo '        return $this->db->getPaginator($sql, $page, $pageSize, $urlTemplate);' . $crlf;
    echo '    }' . $crlf . $crlf . $crlf;
    
endif; //end of @need_read 

echo '}' . $crlf;

echo '?>';
?>